// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lejpclzakbgwmktdnfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlanBjbHpha2Jnd21rdGRuZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTk1NzUsImV4cCI6MjA1ODU3NTU3NX0.B6DbqZysZXMI4uHGUOEi5n_gH4DNWv03vOVBCpkxF3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);